export const FETCH_POSTERS= 'FETCH_POSTERS';
export const FETCH_COLLECIONS= 'FETCH_COLLECTIONS';
export const FETCH_COLLECION= 'FETCH_COLLECTION';

export const FETCH_BASKET_NUMBER = 'FETCH_BASKET_NUMBER';
export const SET_BASKET_NUMBER = 'SET_BASKET_NUMBER';